spring:
  profiles:
    active: h2
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog-master.yaml'
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
